name: Run Python Script

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests xlsxwriter

      - name: Run script
        run: python UserAdministrationActiveUsersOnly.py

      - name: Upload generated Excel file
        uses: actions/upload-artifact@v3
        with:
          name: Active_Users_By_Application
          path: Active_Users_By_Application.xlsx

      - name: Stage and commit changes
        run: |
          git config --local user.email "akousha@torontomu.ca"
          git config --local user.name "Arman Kousha"
          git add Active_Users_By_Application.xlsx
          git commit -m "Add or update generated Excel file" || echo "No changes to commit"

      - name: Pull latest changes and rebase
        run: git pull --rebase origin main

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
