name: Run Python Script

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests xlsxwriter

      - name: Run script
        run: python UserAdministrationActiveUsersOnly.py

      - name: Upload generated Excel file
        uses: actions/upload-artifact@v3
        with:
          name: Active_Users_By_Application
          path: Active_Users_By_Application.xlsx

      - name: Commit and push the Excel file
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add Active_Users_By_Application.xlsx
          git commit -m "Add generated Excel file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
